---
   - name: Reading config
     become: true
     include_vars:
      file: config.yml
      name: config

   - name: Install common parts of the monitoring stack
     become: true
     apt:
      name: "{{ item }}"
      state: present
     loop:
      - ssl-cert
      - apt-transport-https
      - software-properties-common
      - wget
      - adduser
      - libfontconfig1

   - name: Download Grafana
     get_url:
      url: https://dl.grafana.com/oss/release/grafana_9.2.0~beta1_amd64.deb
      dest: /tmp
   - name: Install Grafana from local file
     become: true
     apt:
       deb: /tmp/grafana_9.2.0~beta1_amd64.deb

   - name: Configure Grafana
     become: true
     template:
       src: "grafana.ini.j2"
       dest: "/etc/grafana/grafana.ini"
       backup: true
       mode: 0644
       owner: root
   - name: Configure Grafana user
     become: true
     user:
       name: grafana
       append: true
       groups:
         - ssl-cert
         - root

   - name: Fix Grafana permissions
     become: true
     file:
       path: /usr/share/grafana
       mode: 0755

   - name: Install monitoring stack
     become: true
     apt:
       name: "{{ item }}"
       state: present
     loop:
       - prometheus-alertmanager
       - prometheus

   - name: Configure Prometheus
     become: true
     template:
       src: "prometheus.yml.j2"
       dest: "/etc/prometheus/prometheus.yml"
       backup: true
       mode: 0644
       owner: root

   - name: Configure Alert Manager
     block:
       - name: copy alert_rules.yml
         become: true
         copy:
           src: "alert_rules.yml"
           dest: "/etc/prometheus/alert_rules.yml"
           backup: true
           mode: 0644
           owner: root
       - name: copy alertmanager.yml
         become: true
         template:
           src: "alertmanager.yml.j2"
           dest: "/etc/prometheus/alertmanager.yml"
           backup: true
           mode: 0644
           owner: root

   - name: Start monitoring services
     become: true
     service:
       name: "{{ item }}"
       state: restarted
     loop:
       - prometheus
       - prometheus-node-exporter
       - grafana-server
       - prometheus-alertmanager