---
- hosts: nginx
  gather_facts: no
  roles:
    - nginx
- hosts: mysql_master
  become: true
  gather_facts: no
  roles:
     - { role: mysql,
               mysql_bind_address: "192.168.10.25",
               mysql_db: [{ name: wordpress }],
               mysql_users: [{ name: wordpress, pass: wordpress, priv: "*.*:ALL" }],
               mysql_db_id: 8 }
- hosts: mysql_slave
  become: true
  gather_facts: no
  roles:
     - { role: mysql,
               mysql_bind_address: "192.168.10.34",
               mysql_db: none,
               mysql_users: none,
               mysql_repl_role: slave,
               mysql_repl_master: "192.168.10.25",
               mysql_db_id: 9,
               mysql_repl_user: [{ name: repl, pass: replica }] }
- hosts: wordpress
  become: true
  gather_facts: no
  roles:
    - wordpress
- hosts: git
  become: true
  gather_facts: no
  roles:
    - gitlab
- hosts: git_runner
  become: true
  gather_facts: no
  roles: 
    - gitlab_runner
- hosts: monitor
  become: true
  gather_facts: no
  roles: 
    - monitoring